name: Bintar CI Build

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    name: Build iOS & Android
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        flutter-version: '3.27.3' # Matching King Binz's version

    - name: Get Dependencies
      run: flutter pub get

    - name: Build Android APK
      run: flutter build apk --debug

    - name: Build iOS (No Codesign)
      run: |
        flutter build ios --no-codesign --debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: android-debug-apk
        path: build/app/outputs/flutter-apk/app-debug.apk

    - name: Upload iOS Build
      uses: actions/upload-artifact@v4
      with:
        name: ios-debug-app
        path: build/ios/iphoneos/Runner.app
